<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV8IKuQF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV8IKuQF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV8IKuQF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV8IKuQF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV8IKuQF\App_KernelDevDebugContainer([
    'container.build_hash' => 'V8IKuQF',
    'container.build_id' => '4a77e562',
    'container.build_time' => 1680167609,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV8IKuQF');
